### ISSUE TITLE
Npm package error

### ISSUE THREAD

**Issue by Davide95** [xavierdutreilh/wintersmith-sitemap#4]
Trying to install wintersmith-sitemap on the latest version of wintersmith through npm using `npm install -g wintersmith-sitemap wintersmith-contents` an error appears: 
```
+-- UNMET PEER DEPENDENCY wintersmith@2.x
+-- UNMET PEER DEPENDENCY wintersmith-contents@0.4.0
| `-- minimatch@3.0.0 
`-- wintersmith-sitemap@0.5.0 
  +-- jade@1.11.0 
  `-- lodash@4.7.0 

npm WARN wintersmith-contents@0.4.0 requires a peer of wintersmith@2.x but none was installed.
npm WARN wintersmith-sitemap@0.5.0 requires a peer of wintersmith@^2.0.0 but none was installed.
npm WARN wintersmith-sitemap@0.5.0 requires a peer of wintersmith-contents@^0.3.0 but none was installed.
```

Is there a way to use it or I've to downgrade wintersmith? Sorry for my bad English but I'm not native

**Comment by xavierdutreilh** [comment]
Hi @Davide95.

Thank you for your report.

I made a mistake with `wintersmith-sitemap@0.5.0`. It expects `wintersmith-contents@0.3.0`, while the command `npm install -g wintersmith-sitemap wintersmith-contents` tries to install the latest release of wintersmith-contents (it is `0.4.0`).

Can you try running the command `npm install -g wintersmith-sitemap wintersmith-contents` again? It should now work fine (and grab `wintersmith-sitemap@0.5.1` and `wintersmith-contents@0.4.0`).

Once again, thank you for your report.

**Comment by xavierdutreilh** [comment]
I am closing this issue. If the problem reoccurs again, feel free to reopen this ticket.
